---
name: Lint

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:latest

    steps:
      - uses: actions/checkout@v4

      - name: Print shellcheck version
        run: shellcheck --version

      - name: Run shellcheck
        run: find ./ -type f -name '*.sh' -print -exec shellcheck {} +

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Print shfmt version
        run: shfmt --version

      - name: Run shfmt
        run: find ./ -type f -name '*.sh' -print -exec shfmt --diff --simplify --case-indent --indent 4 {} +
