---
name: Release

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run release.sh
        run: ./release.sh
        shell: bash
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
