---
name: Release

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Run repo.sh --release
        run: ./repo.sh --release
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
